name: Build image
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v2
        id: build

      - name: Test image is runnable
        run: |
          docker run --rm ${{steps.build.outputs.imageid}} config view app


